/* ============================================================
   ANDE — lang.js
   All UI strings. Lesson body text lives in lessons/{id}.js.
   ============================================================ */

const UI_STRINGS = {

  en: {
    nav_curriculum:    'Curriculum',
    nav_materials:     'Materials',
    nav_about:         'About Ande',
    nav_start:         'Start learning',
    hero_h1:           'Mathematics',
    hero_h1_sub:       'simple, precise, and <em>comprehensible</em>.',
    hero_p:            'No jargon first, no proofs before intuition. Each concept starts with <em>why</em>, builds with examples, and gives you something to play with.',
    hero_browse:       'Browse curriculum →',
    hero_try:          'Try a lesson',
    curriculum_label:  'Full curriculum',
    curriculum_title:  'Pick a topic',
    curriculum_sub:    'From number intuitions to calculus. Each section builds from scratch — no assumed knowledge.',
    filter_all:        'All',
    filter_label:      'Filter by area:',
    diff_prompt:       'Choose a difficulty',
    diff_easy:         'Easy',
    diff_medium:       'Medium',
    diff_hard:         'Hard',
    diff_none:         'No lessons available at this difficulty yet.',
    badge_easy:        'Easy',
    badge_medium:      'Medium',
    badge_hard:        'Hard',
    back_curriculum:   '← Back to curriculum',
    coming_soon:       'Lesson coming soon!',
    tasks_title:       'Practice tasks',
    tasks_show:        'Show solution',
    tasks_hide:        'Hide solution',
    footer_copy:       '© 2026– Ande',
    footer_full:       'Ars Numerorum Disciplinam Erudiendi',
    footer_about:      'About Ande',
    /* Area names */
    area_algebra:      'Algebra',
    area_analysis:     'Analysis',
    area_geometrie:    'Geometry',
    area_topologie:    'Topology',
    area_stochastik:   'Stochastics',
  },

  de: {
    nav_curriculum:    'Lehrplan',
    nav_materials:     'Materialien',
    nav_about:         'Über Ande',
    nav_start:         'Jetzt lernen',
    hero_h1:           'Mathematik',
    hero_h1_sub:       'einfach, präzise und <em>verständlich</em>.',
    hero_p:            'Kein Fachjargon zuerst, keine Beweise vor der Intuition. Jedes Konzept beginnt mit dem <em>Warum</em>, baut auf Beispielen auf und bietet etwas zum Ausprobieren.',
    hero_browse:       'Lehrplan erkunden →',
    hero_try:          'Lektion ausprobieren',
    curriculum_label:  'Vollständiger Lehrplan',
    curriculum_title:  'Wähle ein Thema',
    curriculum_sub:    'Von Mengen über den Raum bis hin zum abstrakten Denken.',
    filter_all:        'Alle',
    filter_label:      'Nach Bereich filtern:',
    diff_prompt:       'Schwierigkeitsgrad wählen',
    diff_easy:         'Einfach',
    diff_medium:       'Mittel',
    diff_hard:         'Schwer',
    diff_none:         'Noch keine Lektionen auf diesem Niveau verfügbar.',
    badge_easy:        'Einfach',
    badge_medium:      'Mittel',
    badge_hard:        'Schwer',
    back_curriculum:   '← Zurück zum Lehrplan',
    coming_soon:       'Lektion demnächst verfügbar!',
    tasks_title:       'Aufgaben',
    tasks_show:        'Lösung anzeigen',
    tasks_hide:        'Lösung verbergen',
    footer_copy:       '© 2026– Ande',
    footer_full:       'Ars Numerorum Disciplinam Erudiendi',
    footer_about:      'Über Ande',
    /* Area names */
    area_algebra:      'Algebra',
    area_analysis:     'Analysis',
    area_geometrie:    'Geometrie',
    area_topologie:    'Topologie',
    area_stochastik:   'Stochastik',
  },

};
